.PHONY: clean All

All:
	@echo "----------Building project:[ multiplot - Debug ]----------"
	@"$(MAKE)" -f  "multiplot.mk"
clean:
	@echo "----------Cleaning project:[ multiplot - Debug ]----------"
	@"$(MAKE)" -f  "multiplot.mk" clean
